import { getAuthSession } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { Info } from 'lucide-react';
import { redirect } from 'next/navigation';
import React from 'react'

type Props = {
  params:{
    course_id:string;
  }
};

const CreateChapters = async({params:{course_id}}:Props) => {
  const session = await getAuthSession();
  if(!session?.user){
    return redirect('/course')
  }

  const course = await prisma.course.findUnique({
    where:{
      id:course_id
    },
    include:{
      units:{
        include:{
          chapters: true //prisma way of doing joins, get all teh joins and get hte tree strucutre of all courses , units and chapters
        }
      }
    }
  })
  if(!course){
    return redirect('/create')
  }
  return (
    <div className='pt-6'>
      <div className='flex flex-col items-start max-w-xl mx-auto my-16'>
        <h5 className='text-sm uppercase text-secondary-foreground/60'>
          Course Name
        </h5>
        <h1 className='text-3xl font-bold'>{course.name}</h1>

        <div className='flex p-4 mt-5 border-none bg-secondary'>
          <Info className='w-12 h-12 mr-3 text-blue-400' />
          <div>
            These are the Chapters Generated By Our AI. Have a Look at them and Click on Generate Button to Confirm and continue to Generqate the Course.
          </div>
        </div>

      </div>
    </div>
  )
}

export default CreateChapters